### ISSUE TITLE
Expert mode and additional metrics (F1 score, Precision, or Recall)

### ISSUE THREAD

**Issue by maikherbig** [maikherbig/AIDeveloper#2]
When fitting is initialized with "expert mode" switched on and an additional metric beside Accuracy selected (F1 score, Precision, or Recall), changing any parameter on the 'Expert'-Tab will during fitting cause the following output and error after hitting "Apply at next epoch":
---------------------
Getting dictionary for class_weight
Updating parameter file (meta.xlsx)!
Getting dictionary for class_weight
Change trainable states of model.
Traceback (most recent call last):
  File "AIDeveloper_0.0.6.py", line 251, in run
    result = self.fn(*self.args, **self.kwargs)
  File "AIDeveloper_0.0.6.py", line 8063, in action_fit_model_worker
    history = model_keras.fit(X_batch, Y_batch, batch_size=batchSize_expert, epochs=epochs_expert,verbose=verbose, validation_data=(X_valid, Y_valid),class_weight=class_weight)
  File "keras/engine/training.py", line 1037, in fit
  File "keras/engine/training_arrays.py", line 199, in fit_loop
  File "keras/backend/tensorflow_backend.py", line 2666, in __call__
  File "keras/backend/tensorflow_backend.py", line 2636, in _call
  File "tensorflow/python/client/session.py", line 1382, in __call__
  File "tensorflow/python/framework/errors_impl.py", line 519, in __exit__
tensorflow.python.framework.errors_impl.InvalidArgumentError: You must feed a value for placeholder tensor 'outputTensor_target_1' with dtype float and shape [?,?]
	 [[Node: outputTensor_target_1 = Placeholder[dtype=DT_FLOAT, shape=[?,?], _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]
--------------------------------------

**Comment by maikherbig** [comment]
Solved via 77a5914

**Comment by maikherbig** [comment]
Solved via 77a5914
